postgres:
  APPLY: false
  HOST: localhost
  PORT: 5432
  USER: postgres
  PASSWORD: password
  DBNAME: postgres

mysql:
  APPLY: true
  HOST: localhost
  PORT: 3306
  USER: myuser
  PASSWORD: user_password
  DBNAME: mydb
  ROOT_PASSWORD: root_password