# project.toml

[project]
name = "go-migrations"
version = "v0.1.0"
description = "A CLI tool and Go library for managing database migrations."

[developer]
author = "Lucas Lima Fernandes"
email = "lucaslimafernandes@proton.me"

[repository]
url = "https://github.com/lucaslimafernandes/go-migrations"
